- name: set variables centos/redhat
  set_fact:
    systemd_dir: /usr/lib/systemd/system
    config_dir: /etc/sysconfig
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: set variables debian/ubuntu
  set_fact:
    systemd_dir: /etc/systemd/system
    config_dir: /etc/default
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: ensure rabbitmq stopped
  systemd:
    name: '{{ rabbitmq_systemd }}'
    state: stopped
    enabled: false
  ignore_errors: yes

- name: remove rabbitmq service file
  file:
    path: '{{ systemd_dir }}/{{ rabbitmq_systemd }}'
    state: absent
  notify:
    - reload systemd
